server:
  port: 9095

grpc:
  port: 9090

spring:
  application:
    name: ticket-microservice

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      properties:
        enable:
          idempotence: true
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/ticket-db
      username: postgres
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml


