server:
  port: 9096

grpc:
  client:
    ticketService:
      address: static://localhost:9090
      negotiation-type: plaintext
  port: 9097

spring:
  application:
    name: email-notification-microservice
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/notification-db
      username: postgres
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ticket-created-events
#      key-serializer: org.apache.kafka.common.deserialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.deserializer.JsonSerializer


  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml





