spring:
  application:
    name: email-notification-microservice
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/notification-db
      username: postgres
      password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
server:
  port: 9096
  servlet:
    context-path: /


grpc:
  port: 8089
  client:
    ticketService:
      address: localhost:8088
      negotiation-type: plaintext
